using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;

namespace SpiritKinDesktop;

public partial class MainWindow
{
    private void InitializeMainWindowShell()
    {
        _workspaceController.RefreshLocalServicePorts();
        Title = $"SpiritKin Desktop - {_rootDir}";
        _workspaceController.RenderWorkspaceIdentity(null);
        WorkspaceSidebar.SessionsList.ItemsSource = _sessions;
        WorkspaceSidebar.ProjectsList.ItemsSource = _projects;
        WorkspaceSidebar.CollaborationContextBox.ItemsSource = _contextController.CollaborationContextOptions;
        WorkspaceSidebar.CollaborationProjectScopeBox.ItemsSource = _contextController.CollaborationProjectScopes;
        WorkspaceSidebar.CollaborationSessionScopeBox.ItemsSource = _contextController.CollaborationSessionScopes;
        WorkspaceSidebar.CollaborationThreadsList.ItemsSource = _contextController.CollaborationThreads;
        WorkbenchShell.ManagementPanels.ManagedSessionsList.ItemsSource = _managedSessions;
        WorkbenchShell.ManagementPanels.RightProjectsList.ItemsSource = _managedProjects;
        WorkbenchShell.ManagementPanels.ProjectSessionsList.ItemsSource = _managedProjectSessions;
        WorkspaceSidebar.TasksList.ItemsSource = _tasks;
        WorkbenchShell.ManagementPanels.RightTasksList.ItemsSource = _tasks;
        ChatWorkspace.MessagesList.ItemsSource = _messages;
        InitializeTopicAnchors();
        WorkbenchShell.ManagementPanels.EventsList.ItemsSource = _traceEvents;
        WorkbenchShell.WorkbenchProgressList.ItemsSource = _workbenchController.WorkbenchProgress;
        WorkbenchShell.SourcesList.ItemsSource = _workbenchController.Sources;
        ChatWorkspace.ComposerAttachmentsList.ItemsSource = _composerAttachments;
        ChatWorkspace.EmptyComposerAttachmentsList.ItemsSource = _composerAttachments;
        WorkbenchShell.GitChangesList.ItemsSource = _workbenchController.GitChanges;
        ChatWorkspace.InlineGitChangesList.ItemsSource = _workbenchController.GitChanges;
        WorkbenchShell.ManagementPanels.DiagnosticChecksList.ItemsSource = _diagnosticChecks;
        WorkbenchShell.ManagementPanels.DiagnosticIssuesList.ItemsSource = _diagnosticIssues;
        WorkbenchShell.ManagementPanels.SafetyEventsList.ItemsSource = _safetyController.Events;
        WorkbenchShell.ManagementPanels.ServicesList.ItemsSource = _servicesController.Services;
        WorkbenchShell.ManagementPanels.ServicePortsList.ItemsSource = _servicesController.ServicePorts;
        WorkbenchShell.ManagementPanels.ServiceActionsList.ItemsSource = _servicesController.ServiceActions;
        _servicesController.ResetServicePortRestartPrompt();
        WorkbenchShell.ManagementPanels.LogsList.ItemsSource = _logs;
        WorkbenchShell.ManagementPanels.UnifiedActionLogList.ItemsSource = _actionLogEvents;
        WorkbenchShell.ManagementPanels.SyncClientsList.ItemsSource = _syncClients;
        WorkbenchShell.ManagementPanels.DailyItemsList.ItemsSource = _dailyItems;
        WorkbenchShell.ManagementPanels.ModelProvidersList.ItemsSource = _learningController.ModelProviders;
        WorkbenchShell.ManagementPanels.ProviderManageBox.ItemsSource = _learningController.ProviderDefinitions;
        WorkbenchShell.ManagementPanels.AssistModelProviderBox.ItemsSource = _learningController.ProviderDefinitions;
        WorkbenchShell.ManagementPanels.AssistModelsList.ItemsSource = _learningController.AssistModels;
        WorkbenchShell.ManagementPanels.LearningAssistModelBox.ItemsSource = _learningController.AssistModels;
        WorkbenchShell.ManagementPanels.ReviewCommitteeModelPickerBox.ItemsSource = _learningController.AssistModels;
        WorkbenchShell.ManagementPanels.QuickCommandsList.ItemsSource = _quickCommands;
        WorkbenchShell.ManagementPanels.ModuleManagementModulesList.ItemsSource = _moduleManagementController.Modules;
        WorkbenchShell.ManagementPanels.ModuleManagementActionsList.ItemsSource = _moduleManagementController.Actions;
        WorkbenchShell.ManagementPanels.WorkflowDefinitionCatalogList.ItemsSource = _workflowController.Definitions;
        WorkbenchShell.ManagementPanels.WorkflowSwimlanesList.ItemsSource = _workflowController.Swimlanes;
        WorkbenchShell.ManagementPanels.WorkflowGraphNodesList.ItemsSource = _workflowController.GraphNodes;
        WorkbenchShell.ManagementPanels.WorkflowGraphEdgesList.ItemsSource = _workflowController.GraphEdges;
        WorkbenchShell.ManagementPanels.WorkflowRunsList.ItemsSource = _workflowController.Runs;
        WorkbenchShell.ManagementPanels.WorkflowRunNodesList.ItemsSource = _workflowController.RunNodes;
        WorkbenchShell.ManagementPanels.WorkflowTaskProgressList.ItemsSource = _workflowController.TaskProgress;
        WorkbenchShell.ManagementPanels.WorkflowEditNodesList.ItemsSource = _workflowController.EditNodes;
        WorkbenchShell.ManagementPanels.WorkflowNodeTemplateBox.ItemsSource = _workflowController.NodeTemplates;
        WorkbenchShell.ManagementPanels.WorkflowDependencyNodesList.ItemsSource = _workflowController.DependencyOptions;
        WorkbenchShell.ManagementPanels.WorkflowVersionsList.ItemsSource = _workflowController.Versions;
        WorkbenchShell.ManagementPanels.WorkflowAgentSelectBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.WorkflowNodeAgentBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.SearchGapsList.ItemsSource = _searchManagementController.Gaps;
        WorkbenchShell.ManagementPanels.SearchModelCapabilitiesList.ItemsSource = _searchManagementController.ModelCapabilities;
        WorkbenchShell.ManagementPanels.SearchKnowledgeJobsList.ItemsSource = _searchManagementController.KnowledgeJobs;
        GlobalSearchOverlay.GlobalSearchResultsList.ItemsSource = _globalSearchController.Results;
        WorkbenchShell.ManagementPanels.SkillsList.ItemsSource = _skillsController.Skills;
        WorkbenchShell.ManagementPanels.SkillSourcesList.ItemsSource = _skillsController.SkillSources;
        WorkbenchShell.ManagementPanels.McpServersList.ItemsSource = _mcpManagementController.Servers;
        WorkbenchShell.ManagementPanels.McpToolMappingsList.ItemsSource = _mcpManagementController.ToolMappings;
        WorkbenchShell.ManagementPanels.McpAuditList.ItemsSource = _mcpManagementController.AuditEvents;
        WorkbenchShell.ManagementPanels.SkillOwnerAgentBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.EvolutionPaperOwnerBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.EvolutionVideoOwnerBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.EvolutionLoopStepsList.ItemsSource = _evolutionController.LoopSteps;
        WorkbenchShell.ManagementPanels.EvolutionActionsList.ItemsSource = _evolutionController.Actions;
        WorkbenchShell.ManagementPanels.EvolutionAgentSkillsList.ItemsSource = _evolutionController.AgentSkills;
        WorkbenchShell.ManagementPanels.EvolutionArtifactsList.ItemsSource = _evolutionController.Artifacts;
        WorkbenchShell.ManagementPanels.EvolutionDomainSkillsList.ItemsSource = _evolutionController.DomainSkills;
        WorkbenchShell.ManagementPanels.GrowthRuntimeCandidatesList.ItemsSource = _evolutionController.GrowthCandidates;
        WorkbenchShell.ManagementPanels.GrowthRuntimeCandidatesList.SelectionChanged += (_, _) => _evolutionController.RenderSelectedGrowthCandidate();
        WorkbenchShell.ManagementPanels.MemoryConflictsList.ItemsSource = _memoryManagementController.Conflicts;
        WorkbenchShell.ManagementPanels.MemoryAuditList.ItemsSource = _memoryManagementController.AuditFindings;
        WorkbenchShell.ManagementPanels.ContextSuggestionsList.ItemsSource = _contextController.ContextSuggestions;
        WorkbenchShell.ManagementPanels.ProjectOverviewChangesList.ItemsSource = _contextController.OverviewChanges;
        WorkbenchShell.ManagementPanels.CollaborationTasksList.ItemsSource = _contextController.CollaborationTasks;
        WorkbenchShell.ManagementPanels.CollaborationMessagesList.ItemsSource = _contextController.CollaborationMessages;
        WorkbenchShell.ManagementPanels.CollaborationClaimsList.ItemsSource = _contextController.CollaborationClaims;
        WorkbenchShell.ManagementPanels.CollaborationDecisionsList.ItemsSource = _contextController.CollaborationDecisions;
        WorkbenchShell.ManagementPanels.CollaborationReviewsList.ItemsSource = _contextController.CollaborationReviews;
        WorkbenchShell.ManagementPanels.AgentsList.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.AgentModelSelectBox.ItemsSource = _learningController.AssistModels;
        WorkbenchShell.ManagementPanels.AgentAdapterSelectBox.ItemsSource = _agentsController.AgentAdapters;
        WorkbenchShell.ManagementPanels.ExternalAssistantsList.ItemsSource = _agentsController.ExternalAssistants;
        WorkbenchShell.ManagementPanels.AgentAdaptersList.ItemsSource = _agentsController.AgentAdapters;
        WorkbenchShell.ManagementPanels.KnowledgeBasesList.ItemsSource = _agentsController.KnowledgeBases;
        WorkbenchShell.ManagementPanels.KnowledgeSourcesList.ItemsSource = _agentsController.KnowledgeSources;
        WorkbenchShell.ManagementPanels.KnowledgeBaseOwnerAgentBox.ItemsSource = _agentsController.Agents;
        WorkbenchShell.ManagementPanels.RouteProfilesList.ItemsSource = _agentsController.RouteProfiles;
        WorkbenchShell.ManagementPanels.RemoteTargetsList.ItemsSource = _agentsController.RemoteTargets;
        WorkbenchShell.ManagementPanels.AgentRecommendationsList.ItemsSource = _agentsController.Recommendations;
        WorkspaceSidebar.ApiUrlBox.Text = $"http://127.0.0.1:{_workspaceController.CommandGatewayPort}";
        WorkspaceSidebar.WsUrlBox.Text = $"ws://127.0.0.1:{_workspaceController.EventBridgePort}";
        var sessionToken = (Environment.GetEnvironmentVariable("SPIRITKIN_MOBILE_TOKEN") ?? "").Trim();
        if (sessionToken.Length > 0 && WorkspaceSidebar.TokenBox.Password.Trim().Length == 0)
        {
            // 启动器与命令网关共享同一会话 token；不预填会导致本地发送 401。
            WorkspaceSidebar.TokenBox.Password = sessionToken;
        }
        _learningController.EnsureDefaultProviderDefinitions();
        _learningController.EnsureProviderComboItems();
        _workflowController.EnsureWorkflowNodeTemplates();

        _assistantWorkTimer.Tick += (_, _) => _composerController.TickAssistantWorkTimer();
        _controlMonitorTimer.Tick += async (_, _) =>
        {
            if (_controlMonitorInFlight)
            {
                return;
            }
            _controlMonitorInFlight = true;
            try
            {
                await _mobileManagementController.LoadControlMonitorAsync(
                    autoRepair: true,
                    updateUi: WorkbenchShell.ManagementPanels.MobileManagementPanel.Visibility == Visibility.Visible);
            }
            finally
            {
                _controlMonitorInFlight = false;
            }
        };
        _controlMonitorTimer.Start();
        _contextController.StartSyncTimer();
        // G1 服务看门狗：60s 探测网关健康，连续 2 次不健康后台自动恢复（接活 EnsureLocalServices）。
        StartServiceHealthWatchdog();
        SourceInitialized += MainWindow_SourceInitialized;
        Loaded += MainWindow_Loaded;
        Closed += MainWindow_Closed;
        StateChanged += (_, _) => SyncWindowChromeState();
        TitleBar.DragRequested += (_, _) => DragMove();
        TitleBar.MaximizeRestoreRequested += (_, _) => ToggleWindowMaximized();
        PreviewKeyDown += MainWindow_PreviewKeyDown;
        WorkspaceSidebar.WorkspaceNavListMouseLeftButtonUp += _workspaceController.WorkspaceNavList_MouseLeftButtonUp;
        WorkspaceSidebar.ProjectsListSelectionChanged += _navigationController.ProjectsList_SelectionChanged;
        WorkspaceSidebar.ProjectsListMouseLeftButtonUp += _navigationController.ProjectsList_MouseLeftButtonUp;
        WorkspaceSidebar.CollaborationContextBoxSelectionChanged += _navigationController.CollaborationContextBox_SelectionChanged;
        WorkspaceSidebar.CollaborationProjectScopeBoxSelectionChanged += _navigationController.CollaborationProjectScopeBox_SelectionChanged;
        WorkspaceSidebar.CollaborationSessionScopeBoxSelectionChanged += _navigationController.CollaborationSessionScopeBox_SelectionChanged;
        WorkspaceSidebar.CollaborationThreadsListSelectionChanged += _navigationController.CollaborationThreadsList_SelectionChanged;
        WorkspaceSidebar.CollaborationThreadsListMouseLeftButtonUp += _navigationController.CollaborationThreadsList_MouseLeftButtonUp;
        WorkspaceSidebar.CollaborationThreadArchiveMenuClick += _navigationController.CollaborationThreadArchiveMenu_Click;
        WorkspaceSidebar.CollaborationThreadCopyIdMenuClick += _navigationController.CollaborationThreadCopyIdMenu_Click;
        WorkspaceSidebar.CollaborationThreadDeleteMenuClick += _navigationController.CollaborationThreadDeleteMenu_Click;
        WorkspaceSidebar.CollaborationThreadOpenManagementMenuClick += _navigationController.CollaborationThreadOpenManagementMenu_Click;
        WorkspaceSidebar.CollaborationThreadOpenMenuClick += _navigationController.CollaborationThreadOpenMenu_Click;
        WorkspaceSidebar.SessionsListSelectionChanged += _navigationController.SessionsList_SelectionChanged;
        WorkspaceSidebar.TasksListSelectionChanged += _navigationController.TasksList_SelectionChanged;
        WorkbenchShell.ManagementPanels.AgentAdaptersListSelectionChanged += _agentsController.AgentAdaptersList_SelectionChanged;
        WorkbenchShell.ManagementPanels.AgentsListSelectionChanged += _agentsController.AgentsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.AssistModelsListSelectionChanged += _navigationController.AssistModelsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.MemoryConflictsList.SelectionChanged += (_, _) => _memoryManagementController.RenderSelected();
        WorkbenchShell.ManagementPanels.CollaborationMessagesListSelectionChanged += _contextController.CollaborationMessagesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.CollaborationTasksListSelectionChanged += _contextController.CollaborationTasksList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ContextSuggestionsListSelectionChanged += _navigationController.ContextSuggestionsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.DailyItemsListSelectionChanged += _navigationController.DailyItemsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.DiagnosticIssuesListSelectionChanged += _navigationController.DiagnosticIssuesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ExternalAssistantsListSelectionChanged += _agentsController.ExternalAssistantsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.LogsListSelectionChanged += _navigationController.LogsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ManagedSessionsListSelectionChanged += _navigationController.ManagedSessionsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ModuleManagementActionsListSelectionChanged += _navigationController.ModuleManagementActionsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ModuleManagementModulesListSelectionChanged += _navigationController.ModuleManagementModulesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ProjectOverviewChangesListSelectionChanged += _contextController.ProjectOverviewChangesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ProjectSessionsListSelectionChanged += _navigationController.ProjectSessionsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.QuickCommandsListSelectionChanged += _navigationController.QuickCommandsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.RemoteTargetsListSelectionChanged += _agentsController.RemoteTargetsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.RightProjectsListSelectionChanged += _navigationController.RightProjectsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.RightTasksListSelectionChanged += _navigationController.RightTasksList_SelectionChanged;
        WorkbenchShell.ManagementPanels.RouteProfilesListSelectionChanged += _agentsController.RouteProfilesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ServicePortsListSelectionChanged += (sender, args) => _servicesController.ServicePortsList_SelectionChanged(sender, args, _rendering);
        WorkbenchShell.ManagementPanels.SkillsListSelectionChanged += _navigationController.SkillsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowDefinitionCatalogListSelectionChanged += _workflowController.WorkflowDefinitionCatalogList_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasMouseLeftButtonDown += _workflowController.WorkflowGraphCanvas_MouseLeftButtonDown;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasMouseLeftButtonUp += _workflowController.WorkflowGraphCanvas_MouseLeftButtonUp;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasMouseMove += _workflowController.WorkflowGraphCanvas_MouseMove;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasMouseRightButtonDown += _workflowController.WorkflowGraphCanvas_MouseRightButtonDown;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddAgentNodeMenuClick += _workflowController.WorkflowGraphCanvasAddAgentNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddBranchNodeMenuClick += _workflowController.WorkflowGraphCanvasAddBranchNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddCallbackNodeMenuClick += _workflowController.WorkflowGraphCanvasAddCallbackNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddCustomNodeMenuClick += _workflowController.WorkflowGraphCanvasAddCustomNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddReviewNodeMenuClick += _workflowController.WorkflowGraphCanvasAddReviewNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddSkillNodeMenuClick += _workflowController.WorkflowGraphCanvasAddSkillNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddSubgraphNodeMenuClick += _workflowController.WorkflowGraphCanvasAddSubgraphNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddToolNodeMenuClick += _workflowController.WorkflowGraphCanvasAddToolNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAddWaiterNodeMenuClick += _workflowController.WorkflowGraphCanvasAddWaiterNodeMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasAutoLayoutMenuClick += _workflowController.WorkflowGraphCanvasAutoLayoutMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasResetViewMenuClick += _workflowController.WorkflowGraphCanvasResetViewMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasSaveDefinitionMenuClick += _workflowController.WorkflowGraphCanvasSaveDefinitionMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowGraphCanvasValidateDefinitionMenuClick += _workflowController.WorkflowGraphCanvasValidateDefinitionMenu_Click;
        WorkbenchShell.ManagementPanels.WorkflowRunNodesListSelectionChanged += _workflowController.WorkflowRunNodesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowGraphScrollViewerPreviewMouseWheel += _workflowController.WorkflowGraphScrollViewer_PreviewMouseWheel;
        WorkbenchShell.ManagementPanels.WorkflowGraphScrollViewerSizeChanged += _workflowController.WorkflowGraphScrollViewer_SizeChanged;
        WorkbenchShell.ManagementPanels.WorkflowRunsListSelectionChanged += _workflowController.WorkflowRunsList_SelectionChanged;
        GlobalSearchOverlay.OverlayMouseDown += _globalSearchController.GlobalSearchOverlay_MouseDown;
        GlobalSearchOverlay.PanelMouseDown += _globalSearchController.GlobalSearchPanel_MouseDown;
        GlobalSearchOverlay.SearchTextChanged += _globalSearchController.GlobalSearchBox_TextChanged;
        GlobalSearchOverlay.SearchPreviewKeyDown += _globalSearchController.GlobalSearchBox_PreviewKeyDown;
        GlobalSearchOverlay.ResultsMouseDoubleClick += _globalSearchController.GlobalSearchResultsList_MouseDoubleClick;
        GlobalSearchOverlay.ResultsPreviewKeyDown += _globalSearchController.GlobalSearchResultsList_PreviewKeyDown;
        GlobalSearchOverlay.GlobalSearchCloseButton.Click += (_, _) => _globalSearchController.CloseGlobalSearch();
        WorkspaceSidebar.RefreshButton.Click += async (_, _) => await _runtimeController.RefreshAllAsync();
        WorkspaceSidebar.RefreshSessionsButton.Click += async (_, _) => await _runtimeController.RefreshSessionsFromButtonAsync();
        WorkspaceSidebar.DeleteActiveSessionButton.Click += async (_, _) => await _navigationController.DeleteSelectedSessionAsync();
        WorkspaceSidebar.NewSessionButton.Click += async (_, _) => await _runtimeController.NewSessionAsync();
        WorkspaceSidebar.NewStandaloneSessionButton.Click += async (_, _) => await _runtimeController.NewSessionAsync();
        WorkspaceSidebar.CollaborationMenuButton.Click += (_, _) => OpenCollaborationMenu();
        WorkspaceSidebar.ToggleCollaborationButton.Click += (_, _) => ToggleCollaborationCollapsed();
        WorkspaceSidebar.NewCollaborationThreadButton.Click += (_, _) => _navigationController.NewCollaborationThreadFromSidebar();
        WorkspaceSidebar.ToggleChatsButton.Click += (_, _) => ToggleChatsCollapsed();
        WorkspaceSidebar.ChatsMenuButton.Click += (_, _) => OpenChatsMenu();
        WorkspaceSidebar.ToggleProjectsButton.Click += (_, _) => ToggleProjectsCollapsed();
        WorkspaceSidebar.ProjectsMenuButton.Click += (_, _) => OpenProjectsMenu();
        WorkspaceSidebar.AddProjectButton.Click += async (_, _) => await _runtimeController.AddProjectAsync();
        WorkspaceSidebar.NewProjectSidebarButton.Click += async (_, _) => await _runtimeController.CreateProjectFromSidebarAsync();
        WorkspaceSidebar.AddTaskButton.Click += async (_, _) => await _runtimeController.AddTaskAsync();
        WorkbenchShell.OpenActiveWorkspaceButton.Click += (_, _) => _navigationController.OpenActiveWorkspaceFromStatus();
        WorkbenchShell.ManageActiveWorkspaceButton.Click += (_, _) => _navigationController.ManageActiveWorkspaceFromStatus();
        ChatWorkspace.ChatActionsButton.Click += (_, _) => OpenChatActionsMenu();
        TitleBar.AppMenu.NewChatRequested += (_, _) => _ = _runtimeController.NewSessionAsync();
        TitleBar.AppMenu.NewProjectRequested += (_, _) => _ = _runtimeController.CreateProjectFromSidebarAsync();
        TitleBar.AppMenu.OpenWorkspaceRequested += (_, _) => _navigationController.OpenWorkspaceInExplorer();
        TitleBar.AppMenu.RefreshAllRequested += (_, _) => _ = _runtimeController.RefreshAllAsync();
        TitleBar.AppMenu.ExitRequested += (_, _) => Close();
        TitleBar.AppMenu.UndoRequested += (_, _) => _shellInteractionController.ExecuteTextEditAction("undo");
        TitleBar.AppMenu.FindRequested += (_, _) => _globalSearchController.OpenGlobalSearch();
        TitleBar.AppMenu.DeleteRequested += (_, _) => _ = _navigationController.DeleteCurrentSelectionAsync();
        TitleBar.AppMenu.CutRequested += (_, _) => _shellInteractionController.ExecuteTextEditAction("cut");
        TitleBar.AppMenu.CopyRequested += (_, _) => _shellInteractionController.ExecuteTextEditAction("copy");
        TitleBar.AppMenu.PasteRequested += (_, _) => _shellInteractionController.ExecuteTextEditAction("paste");
        TitleBar.AppMenu.SelectAllRequested += (_, _) => _shellInteractionController.ExecuteTextEditAction("select_all");
        TitleBar.AppMenu.QuickChatRequested += (_, _) => _workspaceController.OpenQuickChat();
        TitleBar.AppMenu.VoiceCallRequested += (_, _) => OpenVoiceCall();
        TitleBar.AppMenu.MusicPlayerRequested += (_, _) => _musicPlayerController.Show();
        TitleBar.AppMenu.ManagementRequested += (_, _) => _workspaceController.OpenManagementPage("tasks");
        TitleBar.AppMenu.ToggleDesktopTtsRequested += (_, _) => ToggleDesktopTtsFromMenu();
        TitleBar.AppMenu.ThemeSystemRequested += (_, _) => ApplyThemeModeFromMenu(ThemeManager.ThemeMode.System);
        TitleBar.AppMenu.ThemeLightRequested += (_, _) => ApplyThemeModeFromMenu(ThemeManager.ThemeMode.Light);
        TitleBar.AppMenu.ThemeDarkRequested += (_, _) => ApplyThemeModeFromMenu(ThemeManager.ThemeMode.Dark);
        TitleBar.ThemeToggleRequested += (_, _) => ApplyThemeModeFromMenu(ThemeManager.CurrentIsDark ? ThemeManager.ThemeMode.Light : ThemeManager.ThemeMode.Dark);
        TitleBar.AppMenu.ShowActiveChatsRequested += (_, _) => ShowChatsWithFilter("active");
        TitleBar.AppMenu.ShowArchivedChatsRequested += (_, _) => ShowChatsWithFilter("archived");
        TitleBar.AppMenu.ShowAllChatsRequested += (_, _) => ShowChatsWithFilter("all");
        TitleBar.AppMenu.OpenTasksRequested += (_, _) => _workspaceController.OpenManagementPage("tasks", "tasks");
        TitleBar.AppMenu.OpenProjectsRequested += (_, _) => _workspaceController.OpenManagementPage("tasks", "projects");
        TitleBar.AppMenu.OpenCommandsRequested += (_, _) => _workspaceController.OpenManagementPage("commands");
        TitleBar.AppMenu.OpenModelsRequested += (_, _) => _workspaceController.OpenManagementPage("models");
        TitleBar.AppMenu.MinimizeRequested += (_, _) => WindowState = WindowState.Minimized;
        TitleBar.AppMenu.MaximizeRestoreRequested += (_, _) => ToggleWindowMaximized();
        TitleBar.AppMenu.RefreshAvatarRequested += (_, _) => _ = _workspaceController.LoadAvatarAsync();
        TitleBar.AppMenu.FloatAvatarRequested += (_, _) => _ = _workspaceController.OpenAvatarFloatWindowAsync();
        TitleBar.AppMenu.OpenDiagnosticsRequested += (_, _) => _workspaceController.OpenManagementPage("diagnostics");
        TitleBar.AppMenu.OpenLogsRequested += (_, _) => _workspaceController.OpenManagementPage("logs");
        TitleBar.AppMenu.OpenServicesRequested += (_, _) => _workspaceController.OpenManagementPage("services");
        TitleBar.AppMenu.AboutRequested += (_, _) => _navigationController.ShowAppDialog("About SpiritKin", "SpiritKin Desktop Workbench", destructive: false, confirmText: "确定", cancelText: "");
        ChatWorkspace.SendButton.Click += async (_, _) => await _runtimeController.SendOrStopCommandAsync();
        ChatWorkspace.EmptySendButton.Click += async (_, _) => await _runtimeController.SendOrStopCommandAsync(ChatWorkspace.EmptyPromptBox.Text);
        ChatWorkspace.EmptyPromptBox.TextChanged += _composerController.EmptyPromptBox_TextChanged;
        ChatWorkspace.ConfirmButton.Click += async (_, _) => await _runtimeController.SendCommandAsync("确认执行");
        ChatWorkspace.CancelButton.Click += async (_, _) => await _runtimeController.SendCommandAsync("取消执行");
        ChatWorkspace.SaveNoteButton.Click += async (_, _) => await _runtimeController.SaveLocalNoteAsync();
        WorkbenchShell.ReloadAvatarButton.Click += async (_, _) => await _workspaceController.LoadAvatarAsync();
        WorkbenchShell.OpenAvatarButton.Click += async (_, _) => await _workspaceController.OpenAvatarFloatWindowAsync();
        ChatWorkspace.ManageQuickCommandsButton.Click += (_, _) => _workspaceController.OpenManagementPage("commands");
        TitleBar.CaptionButtons.MinimizeRequested += (_, _) => WindowState = WindowState.Minimized;
        TitleBar.CaptionButtons.MaximizeRestoreRequested += (_, _) => ToggleWindowMaximized();
        TitleBar.CaptionButtons.CloseRequested += (_, _) => Close();
        WorkbenchShell.ManagementPanels.RefreshDiagnosticsButton.Click += async (_, _) => await _runtimeController.LoadDiagnosticsAsync();
        WorkbenchShell.ManagementPanels.AutoRepairDiagnosticsButton.Click += async (_, _) => await _navigationController.AutoRepairDiagnosticsAsync();
        WorkbenchShell.ManagementPanels.CopyDiagnosticCommandButton.Click += (_, _) => _navigationController.CopySelectedDiagnosticCommand();
        WorkbenchShell.ManagementPanels.RunDiagnosticCommandButton.Click += async (_, _) => await _navigationController.RunSelectedDiagnosticCommandAsync();
        WorkbenchShell.ManagementPanels.RefreshModuleManagementButton.Click += async (_, _) => await _runtimeController.LoadModuleManagementAsync();
        WorkbenchShell.ManagementPanels.ScanModuleManagementButton.Click += async (_, _) => await _runtimeController.ScanModuleManagementAsync();
        WorkbenchShell.ManagementPanels.OpenSelectedModuleButton.Click += (_, _) => _moduleManagementController.OpenSelectedModule();
        WorkbenchShell.ManagementPanels.OpenSelectedModuleActionButton.Click += (_, _) => _moduleManagementController.OpenSelectedAction();
        WorkbenchShell.ManagementPanels.RefreshWorkflowsButton.Click += async (_, _) => await _workflowController.LoadWorkflowsAsync();
        WorkbenchShell.ManagementPanels.NewWorkflowDefinitionButton.Click += (_, _) => _workflowController.NewWorkflowDefinition();
        WorkbenchShell.ManagementPanels.DuplicateWorkflowDefinitionButton.Click += (_, _) => _workflowController.DuplicateWorkflowDefinition();
        WorkbenchShell.ManagementPanels.SaveEcommerceWorkflowButton.Click += async (_, _) => await _workflowController.SaveWorkflowDefinitionAsync();
        WorkbenchShell.ManagementPanels.RestoreBuiltinWorkflowButton.Click += async (_, _) => await _workflowController.RestoreBuiltinWorkflowDefinitionAsync();
        WorkbenchShell.ManagementPanels.DeleteWorkflowDefinitionButton.Click += async (_, _) => await _workflowController.DeleteWorkflowDefinitionAsync();
        WorkbenchShell.ManagementPanels.AddSelectedWorkflowToComposeButton.Click += (_, _) => _workflowController.AddSelectedWorkflowToComposeList();
        WorkbenchShell.ManagementPanels.ComposeWorkflowDefinitionButton.Click += async (_, _) => await _workflowController.ComposeWorkflowDefinitionAsync(startAfterSave: false);
        WorkbenchShell.ManagementPanels.ComposeAndStartWorkflowButton.Click += async (_, _) => await _workflowController.ComposeWorkflowDefinitionAsync(startAfterSave: true);
        WorkbenchShell.ManagementPanels.AddWorkflowNodeButton.Click += (_, _) => _workflowController.AddWorkflowEditNode();
        WorkbenchShell.ManagementPanels.ApplyWorkflowNodeButton.Click += (_, _) => _workflowController.ApplyWorkflowNodeEditor();
        WorkbenchShell.ManagementPanels.DeleteWorkflowNodeButton.Click += (_, _) => _workflowController.DeleteWorkflowEditNode();
        WorkbenchShell.ManagementPanels.ApplyWorkflowTemplateButton.Click += (_, _) => _workflowController.ApplyWorkflowNodeTemplateToEditor();
        WorkbenchShell.ManagementPanels.InsertWorkflowTemplateNodeButton.Click += (_, _) => _workflowController.InsertWorkflowNodeFromTemplate();
        WorkbenchShell.ManagementPanels.InsertCustomWorkflowNodeButton.Click += (_, _) => _workflowController.InsertCustomWorkflowNode();
        WorkbenchShell.ManagementPanels.ConnectWorkflowDependencyButton.Click += (_, _) => _workflowController.AddSelectedWorkflowDependencies();
        WorkbenchShell.ManagementPanels.RemoveWorkflowDependencyButton.Click += (_, _) => _workflowController.RemoveSelectedWorkflowDependencies();
        WorkbenchShell.ManagementPanels.ValidateWorkflowDefinitionButton.Click += (_, _) => _workflowController.ValidateWorkflowDefinitionEditor(showSuccess: true);
        WorkbenchShell.ManagementPanels.AutoLayoutWorkflowButton.Click += (_, _) => _workflowController.AutoLayoutWorkflowEditNodes();
        WorkbenchShell.ManagementPanels.StartWorkflowGraphConnectButton.Click += (_, _) => _workflowController.StartWorkflowGraphConnect();
        WorkbenchShell.ManagementPanels.WorkflowAlignLanesToggle.Checked += (_, _) => _workflowController.ToggleWorkflowLaneAlignment(true);
        WorkbenchShell.ManagementPanels.WorkflowAlignLanesToggle.Unchecked += (_, _) => _workflowController.ToggleWorkflowLaneAlignment(false);
        WorkbenchShell.ManagementPanels.AddWorkflowNodeArgumentButton.Click += (_, _) => _workflowController.AddWorkflowNodeArgumentFromEditor();
        WorkbenchShell.ManagementPanels.WorkflowUndoButton.Click += (_, _) => _workflowController.UndoWorkflowEditor();
        WorkbenchShell.ManagementPanels.WorkflowRedoButton.Click += (_, _) => _workflowController.RedoWorkflowEditor();
        WorkbenchShell.ManagementPanels.WorkflowSelectAllButton.Click += (_, _) => _workflowController.SelectAllWorkflowGraphNodes();
        WorkbenchShell.ManagementPanels.RollbackWorkflowDefinitionButton.Click += async (_, _) => await _workflowController.RollbackWorkflowDefinitionAsync();
        WorkbenchShell.ManagementPanels.RefreshWorkflowGovernanceButton.Click += async (_, _) => await _workflowController.LoadWorkflowsAsync();
        WorkbenchShell.ManagementPanels.WorkflowDesignerJumpToBlueprintButton.Click += (_, _) => _workflowController.JumpToWorkflowBlueprint();
        WorkbenchShell.ManagementPanels.WorkflowBlueprintJumpToDesignerButton.Click += (_, _) => _workflowController.JumpToWorkflowDesigner();
        WorkbenchShell.ManagementPanels.EditSelectedWorkflowNodeButton.Click += (_, _) => _workflowController.OpenWorkflowDesignerForNode(_workflowController.ActiveWorkflowEditNodeId());
        WorkbenchShell.ManagementPanels.AutoLayoutWorkflowGraphButton.Click += (_, _) => _workflowController.AutoLayoutWorkflowEditNodes();
        WorkbenchShell.ManagementPanels.WorkflowZoomOutButton.Click += (_, _) => _workflowController.SetWorkflowGraphZoom(_workflowController.WorkflowGraphZoom - 0.1);
        WorkbenchShell.ManagementPanels.WorkflowZoomInButton.Click += (_, _) => _workflowController.SetWorkflowGraphZoom(_workflowController.WorkflowGraphZoom + 0.1);
        WorkbenchShell.ManagementPanels.WorkflowZoomResetButton.Click += (_, _) => _workflowController.SetWorkflowGraphZoom(1.0);
        WorkbenchShell.ManagementPanels.StartWorkflowRunButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("start_run", _workflowController.BuildWorkflowStartPayload());
        WorkbenchShell.ManagementPanels.WorkflowRunNextDryButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("run_next", _workflowController.BuildWorkflowRunPayload(dryRun: true));
        WorkbenchShell.ManagementPanels.WorkflowRunNextButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("run_next", _workflowController.BuildWorkflowRunPayload(dryRun: false));
        WorkbenchShell.ManagementPanels.WorkflowRunNodeDryButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("run_node", _workflowController.BuildWorkflowNodePayload(dryRun: true));
        WorkbenchShell.ManagementPanels.WorkflowRunNodeButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("run_node", _workflowController.BuildWorkflowNodePayload(dryRun: false));
        WorkbenchShell.ManagementPanels.WorkflowRetryNodeButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("retry_node", _workflowController.BuildWorkflowRetryNodePayload());
        WorkbenchShell.ManagementPanels.WorkflowResetRunButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("reset_run", _workflowController.BuildWorkflowResetRunPayload());
        WorkbenchShell.ManagementPanels.WorkflowAssignAgentButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("assign_agent", _workflowController.BuildWorkflowAgentNodePayload());
        WorkbenchShell.ManagementPanels.WorkflowAssignSelectedNodeButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("assign_agent", _workflowController.BuildWorkflowAgentNodePayload());
        WorkbenchShell.ManagementPanels.WorkflowClaimNodeButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("claim_agent_task", _workflowController.BuildWorkflowAgentNodePayload());
        WorkbenchShell.ManagementPanels.WorkflowCompleteNodeButton.Click += async (_, _) => await _workflowController.CompleteOrSignalWorkflowNodeAsync();
        WorkbenchShell.ManagementPanels.WorkflowApproveNodeButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("approve_review", _workflowController.BuildWorkflowReviewNodePayload());
        WorkbenchShell.ManagementPanels.ArchiveWorkflowRunButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("archive_run", _workflowController.BuildWorkflowRunManagementPayload());
        WorkbenchShell.ManagementPanels.CleanupWorkflowRunsButton.Click += async (_, _) => await _workflowController.WorkflowActionAsync("cleanup_runs", _workflowController.BuildWorkflowRunManagementPayload(keepRecent: 30));
        WorkbenchShell.ManagementPanels.WorkflowEditNodesList.SelectionChanged += _workflowController.WorkflowEditNodesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowDependencyNodesList.SelectionChanged += _workflowController.WorkflowDependencyNodesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowNodeTypeBox.SelectionChanged += _workflowController.WorkflowNodeTypeBox_SelectionChanged;
        WorkbenchShell.ManagementPanels.WorkflowNodeArgumentsBox.TextChanged += _workflowController.WorkflowNodeArgumentsBox_TextChanged;
        WorkbenchShell.ManagementPanels.RefreshSearchManagementButton.Click += async (_, _) => await _searchManagementController.LoadAsync();
        WorkbenchShell.ManagementPanels.IndexUnindexedKnowledgeButton.Click += async (_, _) => await _searchManagementController.IndexUnindexedKnowledgeAsync();
        WorkbenchShell.ManagementPanels.SaveSearchRuntimeButton.Click += async (_, _) => await _searchManagementController.SaveRuntimeConfigAsync();
        WorkbenchShell.ManagementPanels.RefreshSkillsButton.Click += async (_, _) => await _skillsController.LoadSkillsAsync();
        WorkbenchShell.ManagementPanels.NewSkillButton.Click += (_, _) => _skillsController.NewSkill();
        WorkbenchShell.ManagementPanels.SaveSkillButton.Click += async (_, _) => await _skillsController.SaveSkillAsync();
        WorkbenchShell.ManagementPanels.DeleteSkillButton.Click += async (_, _) => await _skillsController.DeleteSkillAsync();
        WorkbenchShell.ManagementPanels.PromoteSkillButton.Click += async (_, _) => await _skillsController.SkillActionAsync("promote");
        WorkbenchShell.ManagementPanels.ReviewSkillsButton.Click += async (_, _) => await _skillsController.SkillActionAsync("review_candidates");
        WorkbenchShell.ManagementPanels.BindSkillUiButton.Click += async (_, _) => await _skillsController.BindSkillUiAsync();
        WorkbenchShell.ManagementPanels.ExportSkillButton.Click += async (_, _) => await _skillsController.SkillActionAsync("export");
        WorkbenchShell.ManagementPanels.DryRunSkillButton.Click += async (_, _) => await _skillsController.RunSelectedSkillAsync(dryRun: true);
        WorkbenchShell.ManagementPanels.RunSkillButton.Click += async (_, _) => await _skillsController.RunSelectedSkillAsync(dryRun: false);
        WorkbenchShell.ManagementPanels.RegisterSkillSourceButton.Click += async (_, _) => await _skillsController.RegisterSkillSourceAsync();
        WorkbenchShell.ManagementPanels.SyncSkillSourceButton.Click += async (_, _) => await _skillsController.SkillSourceActionAsync("sync_source");
        WorkbenchShell.ManagementPanels.ImportSkillSourceButton.Click += async (_, _) => await _skillsController.SkillSourceActionAsync("import_source_candidates");
        WorkbenchShell.ManagementPanels.DeleteSkillSourceButton.Click += async (_, _) => await _skillsController.DeleteSkillSourceAsync();
        WorkbenchShell.ManagementPanels.SyncOpenClawSkillsButton.Click += async (_, _) => await _skillsController.SyncOpenClawSkillsAsync();
        WorkbenchShell.ManagementPanels.SaveSkillSourcePolicyButton.Click += async (_, _) => await _skillsController.SaveSkillSourcePolicyAsync();
        WorkbenchShell.ManagementPanels.SkillSourcesList.SelectionChanged += (_, _) => _skillsController.RenderSelectedSkillSourceEditor();
        WorkbenchShell.ManagementPanels.RefreshMcpManagementButton.Click += async (_, _) => await _mcpManagementController.LoadAsync();
        WorkbenchShell.ManagementPanels.NewMcpServerButton.Click += (_, _) => _mcpManagementController.NewServer();
        WorkbenchShell.ManagementPanels.SaveMcpServerButton.Click += async (_, _) => await _mcpManagementController.SaveServerAsync();
        WorkbenchShell.ManagementPanels.ApproveMcpServerButton.Click += async (_, _) => await _mcpManagementController.ServerActionAsync("approve_server");
        WorkbenchShell.ManagementPanels.RejectMcpServerButton.Click += async (_, _) => await _mcpManagementController.ServerActionAsync("reject_server");
        WorkbenchShell.ManagementPanels.EnableMcpServerButton.Click += async (_, _) => await _mcpManagementController.ServerActionAsync("enable_server");
        WorkbenchShell.ManagementPanels.DisableMcpServerButton.Click += async (_, _) => await _mcpManagementController.ServerActionAsync("disable_server");
        WorkbenchShell.ManagementPanels.DeleteMcpServerButton.Click += async (_, _) => await _mcpManagementController.DeleteServerAsync();
        WorkbenchShell.ManagementPanels.McpServersList.SelectionChanged += (_, _) => _mcpManagementController.OnServerSelectionChanged();
        WorkbenchShell.ManagementPanels.RefreshMobileManagementButton.Click += async (_, _) => await _mobileManagementController.LoadMobileManagementAsync();
        WorkbenchShell.ManagementPanels.StartAndroidEndpointButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("start_android_endpoint");
        WorkbenchShell.ManagementPanels.RestartAndroidEndpointButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("restart_android_endpoint");
        WorkbenchShell.ManagementPanels.StartIosEndpointButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("start_ios_endpoint");
        WorkbenchShell.ManagementPanels.RestartIosEndpointButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("restart_ios_endpoint");
        WorkbenchShell.ManagementPanels.ReconnectAndroidAdbButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("adb_reconnect", _mobileManagementController.BuildMobileAdbPayload());
        WorkbenchShell.ManagementPanels.InstallAndroidBridgeButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("install_android_bridge", _mobileManagementController.BuildMobileAdbPayload());
        WorkbenchShell.ManagementPanels.ApproveAndroidApkButton.Click += async (_, _) => await _mobileManagementController.ApproveAndroidApkReleaseAsync();
        WorkbenchShell.ManagementPanels.StartAndroidLifecycleWorkflowButton.Click += async (_, _) => await _mobileManagementController.StartAndroidLifecycleWorkflowAsync();
        WorkbenchShell.ManagementPanels.QueueAndroidCommandButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("enqueue_android_command", _mobileManagementController.BuildMobileCommandPayload());
        WorkbenchShell.ManagementPanels.ClearAndroidCommandsButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("clear_android_commands", _mobileManagementController.BuildClearMobileCommandPayload());
        WorkbenchShell.ManagementPanels.CleanupExpiredMobileArtifactsButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("cleanup_mobile_artifacts", new Dictionary<string, object?> { ["expired_only"] = true });
        WorkbenchShell.ManagementPanels.CleanupOldMobileArtifactsButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("cleanup_mobile_artifacts", new Dictionary<string, object?> { ["expired_only"] = false, ["keep_recent"] = 200 });
        WorkbenchShell.ManagementPanels.MobileWorkspaceDevicesList.SelectionChanged += _mobileManagementController.MobileWorkspaceDevicesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ApproveAndroidPairingRequestButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("approve_pairing_request", _mobileManagementController.BuildPairingRequestPayload(includeRequestId: true));
        WorkbenchShell.ManagementPanels.RejectAndroidPairingRequestButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("reject_pairing_request", _mobileManagementController.BuildPairingRequestPayload(includeRequestId: true));
        WorkbenchShell.ManagementPanels.ClearWorkspacePairingHistoryButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("clear_pairing_history", _mobileManagementController.BuildPairingRequestPayload(includeRequestId: false));
        WorkbenchShell.ManagementPanels.ClearWorkspaceBindingHistoryButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("clear_binding_history", _mobileManagementController.BuildPairingRequestPayload(includeRequestId: false));
        WorkbenchShell.ManagementPanels.EnableDeviceWorkflowButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("add_device_workflow", _mobileManagementController.BuildDeviceWorkflowPayload(enabled: true));
        WorkbenchShell.ManagementPanels.PauseDeviceWorkflowButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("set_device_workflow_state", _mobileManagementController.BuildDeviceWorkflowPayload(enabled: false));
        WorkbenchShell.ManagementPanels.RepairDeviceWorkflowStatusButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("repair_device_workflow", _mobileManagementController.BuildDeviceWorkflowRepairPayload("status"));
        WorkbenchShell.ManagementPanels.RepairDeviceWorkflowPddButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("repair_device_workflow", _mobileManagementController.BuildDeviceWorkflowRepairPayload("open_pdd"));
        WorkbenchShell.ManagementPanels.RepairDeviceWorkflowAccessibilityButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("repair_device_workflow", _mobileManagementController.BuildDeviceWorkflowRepairPayload("accessibility_settings"));
        WorkbenchShell.ManagementPanels.RepairDeviceWorkflowScreenshotButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("repair_device_workflow", _mobileManagementController.BuildDeviceWorkflowRepairPayload("screenshot_permission"));
        WorkbenchShell.ManagementPanels.DeleteDeviceWorkflowButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("delete_device_workflow", _mobileManagementController.BuildDeviceWorkflowPayload(enabled: false));
        WorkbenchShell.ManagementPanels.RefreshStateMaintenanceButton.Click += async (_, _) => await _mobileManagementController.LoadStateMaintenanceAsync();
        WorkbenchShell.ManagementPanels.CleanupStateMaintenanceButton.Click += async (_, _) => await _mobileManagementController.StateMaintenanceActionAsync("cleanup_all");
        WorkbenchShell.ManagementPanels.CopyAndroidReceiverUrlButton.Click += (_, _) => _mobileManagementController.CopyMobileText(WorkbenchShell.ManagementPanels.MobileAndroidReceiverUrlBox.Text, "Android receiver URL 已复制。");
        WorkbenchShell.ManagementPanels.GenerateAndroidPairingButton.Click += async (_, _) => await _mobileManagementController.MobileManagementActionAsync("create_android_pairing", _mobileManagementController.BuildAndroidPairingPayload());
        WorkbenchShell.ManagementPanels.CopyAndroidPairingBundleButton.Click += (_, _) => _mobileManagementController.CopyMobileText(_mobileManagementController.BuildAndroidPairingBundleText(), "Android 绑定信息已复制。");
        WorkbenchShell.ManagementPanels.CopyAndroidPairingTokenButton.Click += (_, _) => _mobileManagementController.CopyMobileText(WorkbenchShell.ManagementPanels.MobilePairingTokenBox.Text, "Android pairing token 已复制。");
        WorkbenchShell.ManagementPanels.OpenAndroidPairingPageButton.Click += (_, _) => _mobileManagementController.OpenMobileUrl(WorkbenchShell.ManagementPanels.MobilePairingPageUrlBox.Text, "Android 配对页");
        WorkbenchShell.ManagementPanels.CopyIosBaseUrlButton.Click += (_, _) => _mobileManagementController.CopyMobileText(WorkbenchShell.ManagementPanels.MobileIosBaseUrlBox.Text, "iOS base URL 已复制。");
        WorkbenchShell.ManagementPanels.CopyIosNativeDeepLinkButton.Click += (_, _) => _mobileManagementController.CopyMobileText(WorkbenchShell.ManagementPanels.MobileIosNativeDeepLinkBox.Text, "iOS native deep link 已复制。");
        WorkbenchShell.ManagementPanels.CopyIosNativeConfigButton.Click += (_, _) => _mobileManagementController.CopyMobileText(WorkbenchShell.ManagementPanels.MobileIosNativeConfigBox.Text, "iOS native config JSON 已复制。");
        WorkbenchShell.ManagementPanels.CopyIosNativeBundleButton.Click += (_, _) => _mobileManagementController.CopyMobileText(_mobileManagementController.BuildIosNativeConfigBundleText(), "iOS native terminal 配置信息已复制。");
        WorkbenchShell.ManagementPanels.OpenIosPairingPageButton.Click += (_, _) => _mobileManagementController.OpenMobileUrl(WorkbenchShell.ManagementPanels.MobileIosPairingUrlBox.Text, "iOS 配对页");
        ChatWorkspace.SafetyStopButton.Click += async (_, _) => await _safetyController.SetStopAsync(active: true);
        ChatWorkspace.SafetyResumeButton.Click += async (_, _) => await _safetyController.SetStopAsync(active: false);
        WorkbenchShell.ManagementPanels.RefreshServicesButton.Click += async (_, _) => await _servicesController.LoadServicesAsync();
        WorkbenchShell.ManagementPanels.SaveServicePortButton.Click += async (_, _) => await _servicesController.SaveSelectedServicePortAsync();
        WorkbenchShell.ManagementPanels.ResetServicePortButton.Click += async (_, _) => await _servicesController.ResetSelectedServicePortAsync();
        WorkbenchShell.ManagementPanels.RepairServicePortsButton.Click += async (_, _) => await _servicesController.RepairServicePortsAsync();
        WorkbenchShell.ManagementPanels.RestartPortServicesButton.Click += async (_, _) => await _servicesController.RestartPendingPortServicesAsync();
        WorkbenchShell.ManagementPanels.ApplyServicePortClientUrlsButton.Click += (_, _) => _servicesController.ApplyPendingServicePortClientUrls();
        WorkbenchShell.ManagementPanels.CopyServicePortMigrationButton.Click += (_, _) => _servicesController.CopyServicePortMigrationText();
        WorkbenchShell.ManagementPanels.SaveProjectPortProfileButton.Click += async (_, _) => await _servicesController.SaveProjectPortProfileAsync();
        WorkbenchShell.ManagementPanels.ApplyProjectPortProfileButton.Click += async (_, _) => await _servicesController.ApplyProjectPortProfileAsync();
        WorkbenchShell.ManagementPanels.DeleteProjectPortProfileButton.Click += async (_, _) => await _servicesController.DeleteProjectPortProfileAsync();
        WorkbenchShell.ManagementPanels.RefreshLogsButton.Click += async (_, _) => await _runtimeController.LoadLogsAsync();
        WorkbenchShell.ManagementPanels.OpenSelectedLogButton.Click += (_, _) => _navigationController.OpenSelectedLogFile();
        WorkbenchShell.ManagementPanels.OpenSelectedLogFolderButton.Click += (_, _) => _navigationController.OpenSelectedLogFolder();
        WorkbenchShell.ManagementPanels.ArchiveSelectedLogButton.Click += async (_, _) => await _navigationController.ArchiveSelectedLogAsync();
        WorkbenchShell.ManagementPanels.DeleteSelectedLogButton.Click += async (_, _) => await _navigationController.DeleteSelectedLogAsync();
        WorkbenchShell.ManagementPanels.RefreshDailyButton.Click += async (_, _) => await _runtimeController.LoadDailyAsync();
        WorkbenchShell.ManagementPanels.OpenDailyItemButton.Click += (_, _) => _navigationController.OpenSelectedDailyItem();
        WorkbenchShell.ManagementPanels.StartDailyTaskButton.Click += async (_, _) => await _navigationController.UpdateSelectedDailyTaskStatusAsync("running");
        WorkbenchShell.ManagementPanels.CompleteDailyTaskButton.Click += async (_, _) => await _navigationController.UpdateSelectedDailyTaskStatusAsync("complete");
        WorkbenchShell.ManagementPanels.BlockDailyTaskButton.Click += async (_, _) => await _navigationController.UpdateSelectedDailyTaskStatusAsync("blocked");
        WorkbenchShell.ManagementPanels.RefreshSyncButton.Click += async (_, _) => await _runtimeController.LoadSyncAsync();
        WorkbenchShell.ManagementPanels.ClearSyncEventsButton.Click += async (_, _) => await _runtimeController.SyncActionAsync("clear_events");
        WorkbenchShell.ManagementPanels.ClearPendingButton.Click += async (_, _) => await _runtimeController.SyncActionAsync("clear_pending");
        WorkbenchShell.ManagementPanels.CompactSessionsButton.Click += async (_, _) => await _runtimeController.SyncActionAsync("compact_sessions");
        WorkbenchShell.ManagementPanels.SaveLearningButton.Click += async (_, _) => await _learningController.SaveLearningRecordAsync();
        WorkbenchShell.ManagementPanels.NewQuickCommandButton.Click += (_, _) => _navigationController.NewQuickCommand();
        WorkbenchShell.ManagementPanels.SaveQuickCommandButton.Click += async (_, _) => await _navigationController.SaveQuickCommandAsync();
        WorkbenchShell.ManagementPanels.DeleteQuickCommandButton.Click += async (_, _) => await _navigationController.DeleteQuickCommandAsync();
        WorkbenchShell.ManagementPanels.ExportLearningDatasetButton.Click += async (_, _) => await _learningController.ExportLearningDatasetAsync();
        WorkbenchShell.ManagementPanels.BuildReviewPromptButton.Click += async (_, _) => await _learningController.BuildReviewPromptAsync();
        WorkbenchShell.ManagementPanels.ModelReviewButton.Click += async (_, _) => await _learningController.RequestModelReviewAsync();
        WorkbenchShell.ManagementPanels.MultiModelReviewButton.Click += async (_, _) => await _learningController.RequestMultiModelReviewAsync();
        WorkbenchShell.ManagementPanels.RunSchedulerBenchmarkButton.Click += async (_, _) => await _learningController.RunSchedulerBenchmarkAsync();
        WorkbenchShell.ManagementPanels.RefreshMemoryButton.Click += async (_, _) => await _memoryManagementController.LoadAsync();
        WorkbenchShell.ManagementPanels.MemoryConflictFilterBox.SelectionChanged += (_, _) => _memoryManagementController.ApplyFilter();
        WorkbenchShell.ManagementPanels.ApplyMemoryResolutionButton.Click += async (_, _) => await _memoryManagementController.ResolveSelectedAsync();
        WorkbenchShell.ManagementPanels.RefreshEvolutionButton.Click += async (_, _) => await _evolutionController.LoadAsync();
        WorkbenchShell.ManagementPanels.RefreshRuntimeContinuityButton.Click += async (_, _) => await _evolutionController.LoadRuntimeContinuityAsync();
        WorkbenchShell.ManagementPanels.RequestRuntimeMigrationButton.Click += async (_, _) => await _evolutionController.RequestRuntimeMigrationAsync();
        WorkbenchShell.ManagementPanels.ExportEvolutionDatasetButton.Click += async (_, _) => await _evolutionController.ActionAsync("export_self_training_dataset");
        WorkbenchShell.ManagementPanels.BuildEvolutionCloudPackageButton.Click += async (_, _) => await _evolutionController.ActionAsync("build_cloud_training_package");
        WorkbenchShell.ManagementPanels.EnforceSkillOwnershipButton.Click += async (_, _) => await _evolutionController.ActionAsync("enforce_skill_ownership");
        WorkbenchShell.ManagementPanels.IngestPaperSkillButton.Click += async (_, _) => await _evolutionController.IngestArtifactAsync("paper");
        WorkbenchShell.ManagementPanels.IngestVideoSkillButton.Click += async (_, _) => await _evolutionController.IngestArtifactAsync("video");
        WorkbenchShell.ManagementPanels.SeedDomainSkillTemplatesButton.Click += async (_, _) => await _evolutionController.ActionAsync("seed_domain_skill_templates");
        WorkbenchShell.ManagementPanels.SaveEvolutionReviewGateButton.Click += async (_, _) => await _evolutionController.SaveReviewGateAsync();
        WorkbenchShell.ManagementPanels.GrowthAdvanceStageButton.Click += async (_, _) => await _evolutionController.GrowthActionAsync("advance_stage");
        WorkbenchShell.ManagementPanels.GrowthPrepareBuilderButton.Click += async (_, _) => await _evolutionController.PrepareBuilderArtifactAsync();
        WorkbenchShell.ManagementPanels.GrowthPrepareSandboxBundleButton.Click += async (_, _) => await _evolutionController.PrepareSandboxBundleAsync();
        WorkbenchShell.ManagementPanels.GrowthResearchButton.Click += async (_, _) => await _evolutionController.ResearchGrowthCandidateAsync();
        WorkbenchShell.ManagementPanels.GrowthVerifyBuilderButton.Click += async (_, _) => await _evolutionController.VerifyBuilderArtifactAsync();
        WorkbenchShell.ManagementPanels.GrowthExecuteSandboxButton.Click += async (_, _) => await _evolutionController.ExecuteBuilderSandboxAsync();
        WorkbenchShell.ManagementPanels.GrowthRunBenchmarkButton.Click += async (_, _) => await _evolutionController.RecordCandidateBenchmarkAsync();
        WorkbenchShell.ManagementPanels.GrowthRunModelJuryButton.Click += async (_, _) => await _evolutionController.RunModelJuryAsync();
        WorkbenchShell.ManagementPanels.GrowthApproveButton.Click += async (_, _) => await _evolutionController.GrowthActionAsync("review_candidate", "approve");
        WorkbenchShell.ManagementPanels.GrowthRejectButton.Click += async (_, _) => await _evolutionController.GrowthActionAsync("review_candidate", "reject");
        WorkbenchShell.ManagementPanels.GrowthRegisterButton.Click += async (_, _) => await _evolutionController.GrowthActionAsync("register_candidate");
        WorkbenchShell.ManagementPanels.GrowthEscalateButton.Click += async (_, _) => await _evolutionController.EscalateGrowthCandidateAsync();
        WorkbenchShell.ManagementPanels.NewAssistModelButton.Click += (_, _) => _learningController.NewAssistModel();
        WorkbenchShell.ManagementPanels.BrowseModelLibraryButton.Click += (_, _) => _learningController.BrowseModelLibraryPath();
        WorkbenchShell.ManagementPanels.ProviderServiceButton.Click += (_, _) => _learningController.ToggleSelectedProviderService();
        WorkbenchShell.ManagementPanels.SyncProviderModelsButton.Click += async (_, _) => await _learningController.SyncSelectedProviderModelsAsync(promptForPath: false);
        WorkbenchShell.ManagementPanels.TestProviderButton.Click += async (_, _) => await _learningController.TestSelectedProviderAsync();
        WorkbenchShell.ManagementPanels.SaveAssistModelButton.Click += async (_, _) => await _learningController.SaveAssistModelAsync();
        WorkbenchShell.ManagementPanels.DeleteAssistModelButton.Click += async (_, _) => await _learningController.DeleteAssistModelAsync();
        WorkbenchShell.ManagementPanels.RefreshAssistModelsButton.Click += async (_, _) => await _learningController.LoadLearningAsync();
        WorkbenchShell.ManagementPanels.SaveReviewCommitteePolicyButton.Click += async (_, _) => await _learningController.SaveReviewCommitteePolicyAsync();
        WorkbenchShell.ManagementPanels.RefreshGovernanceButton.Click += async (_, _) => await _governanceController.LoadAsync();
        WorkbenchShell.ManagementPanels.ToolAuthorizationList.SelectionChanged += (_, _) => _governanceController.RenderSelectedToolAuthorization();
        WorkbenchShell.ManagementPanels.SaveToolAuthorizationButton.Click += async (_, _) => await _governanceController.SaveToolAuthorizationAsync();
        WorkbenchShell.ManagementPanels.ScheduledIntentsList.SelectionChanged += (_, _) => _governanceController.RenderSelectedScheduledIntent();
        WorkbenchShell.ManagementPanels.ScheduledTriggerTypeBox.SelectionChanged += (_, _) => _governanceController.SyncScheduledTriggerFields();
        WorkbenchShell.ManagementPanels.NewScheduledIntentButton.Click += (_, _) => _governanceController.NewScheduledIntent();
        WorkbenchShell.ManagementPanels.SaveScheduledIntentButton.Click += async (_, _) => await _governanceController.SaveScheduledIntentAsync();
        WorkbenchShell.ManagementPanels.PauseScheduledIntentButton.Click += async (_, _) => await _governanceController.RunScheduledIntentActionAsync("pause");
        WorkbenchShell.ManagementPanels.ResumeScheduledIntentButton.Click += async (_, _) => await _governanceController.RunScheduledIntentActionAsync("resume");
        WorkbenchShell.ManagementPanels.RunScheduledIntentButton.Click += async (_, _) => await _governanceController.RunScheduledIntentActionAsync("run_now");
        WorkbenchShell.ManagementPanels.CancelScheduledIntentButton.Click += async (_, _) => await _governanceController.RunScheduledIntentActionAsync("cancel");
        WorkbenchShell.ManagementPanels.FillReviewCommitteeModelsButton.Click += (_, _) => _learningController.FillReviewCommitteeModelsFromEnabled();
        WorkbenchShell.ManagementPanels.ReviewCommitteeModelPickerBox.SelectionChanged += (_, _) => _learningController.AppendReviewCommitteeModelFromPicker();
        WorkbenchShell.ManagementPanels.ReviewCommitteeRolePickerBox.SelectionChanged += (_, _) => _learningController.AppendReviewCommitteeRoleFromPicker();
        WorkbenchShell.ManagementPanels.ReviewCommitteeActionPickerBox.SelectionChanged += (_, _) => _learningController.AppendReviewCommitteeActionFromPicker();
        WorkbenchShell.ManagementPanels.ProviderManageBox.SelectionChanged += (_, _) => _learningController.SyncProviderManagerSelection();
        WorkbenchShell.ManagementPanels.ProviderManageBox.DropDownClosed += (_, _) => _learningController.RefreshProviderComboDisplay();
        WorkbenchShell.ManagementPanels.AssistModelProviderBox.SelectionChanged += (_, _) => _learningController.SyncAssistProviderSelection();
        WorkbenchShell.ManagementPanels.AssistModelProviderBox.DropDownClosed += (_, _) => _learningController.RefreshProviderComboDisplay();
        WorkbenchShell.ManagementPanels.SaveContextPolicyButton.Click += async (_, _) => await _contextController.SaveContextPolicyAsync();
        WorkbenchShell.ManagementPanels.CopyContextSuggestionButton.Click += (_, _) => _navigationController.CopySelectedContextSuggestion();
        WorkbenchShell.ManagementPanels.OpenContextOverviewButton.Click += (_, _) => _workspaceController.OpenManagementPage("overview");
        WorkbenchShell.ManagementPanels.CreateSessionFromPanelButton.Click += async (_, _) => await _runtimeController.NewSessionAsync();
        WorkbenchShell.ManagementPanels.SaveSessionButton.Click += async (_, _) => await _navigationController.SaveSelectedSessionAsync();
        WorkbenchShell.ManagementPanels.ArchiveSessionButton.Click += async (_, _) => await _navigationController.ArchiveSelectedSessionAsync();
        WorkbenchShell.ManagementPanels.DeleteSessionButton.Click += async (_, _) => await _navigationController.DeleteSelectedSessionAsync();
        WorkbenchShell.ManagementPanels.OpenManagedSessionButton.Click += (_, _) => _navigationController.OpenSelectedManagedSession();
        WorkbenchShell.ManagementPanels.MoveSessionToChatsButton.Click += async (_, _) => await _navigationController.MoveSelectedManagedSessionToChatsAsync();
        WorkbenchShell.ManagementPanels.PinManagedSessionButton.Click += async (_, _) => await _navigationController.ToggleSelectedManagedSessionPinnedAsync();
        WorkbenchShell.ManagementPanels.CreateProjectFromPanelButton.Click += async (_, _) => await _runtimeController.AddProjectFromEditorAsync();
        WorkbenchShell.ManagementPanels.SaveProjectButton.Click += async (_, _) => await _navigationController.SaveSelectedProjectAsync();
        WorkbenchShell.ManagementPanels.ArchiveProjectButton.Click += async (_, _) => await _navigationController.ToggleSelectedProjectArchiveAsync();
        WorkbenchShell.ManagementPanels.DeleteProjectButton.Click += async (_, _) => await _navigationController.DeleteSelectedProjectAsync();
        WorkbenchShell.ManagementPanels.OpenProjectWorkspaceButton.Click += (_, _) => _navigationController.OpenSelectedProjectWorkspace();
        WorkbenchShell.ManagementPanels.DetectProjectRuntimeButton.Click += (_, _) => _navigationController.DetectSelectedProjectRuntimeProfile();
        WorkbenchShell.ManagementPanels.RunProjectStartCommandButton.Click += async (_, _) => await _navigationController.RunSelectedProjectStartCommandAsync();
        WorkbenchShell.ManagementPanels.NewProjectSessionButton.Click += async (_, _) => await _navigationController.NewSessionForSelectedProjectAsync();
        WorkbenchShell.ManagementPanels.RenameProjectSessionButton.Click += async (_, _) => await _navigationController.RenameSelectedProjectSessionAsync();
        WorkbenchShell.ManagementPanels.ArchiveProjectSessionButton.Click += async (_, _) => await _navigationController.ToggleSelectedProjectSessionArchiveAsync();
        WorkbenchShell.ManagementPanels.DeleteProjectSessionButton.Click += async (_, _) => await _navigationController.DeleteSelectedProjectSessionAsync();
        WorkbenchShell.ManagementPanels.CreateTaskFromPanelButton.Click += async (_, _) => await _runtimeController.AddTaskFromEditorAsync();
        WorkbenchShell.ManagementPanels.SaveTaskButton.Click += async (_, _) => await _navigationController.SaveSelectedTaskAsync();
        WorkbenchShell.ManagementPanels.DeleteTaskButton.Click += async (_, _) => await _navigationController.DeleteSelectedTaskAsync();
        WorkbenchShell.ManagementPanels.RefreshProjectOverviewButton.Click += async (_, _) => await _contextController.RefreshProjectOverviewAsync();
        WorkbenchShell.ManagementPanels.SaveProjectOverviewButton.Click += async (_, _) => await _contextController.SaveProjectOverviewAsync();
        WorkbenchShell.ManagementPanels.ApproveOverviewChangeButton.Click += async (_, _) => await _contextController.ReviewSelectedOverviewChangeAsync("approve");
        WorkbenchShell.ManagementPanels.RejectOverviewChangeButton.Click += async (_, _) => await _contextController.ReviewSelectedOverviewChangeAsync("reject");
        WorkbenchShell.ManagementPanels.OpenProjectOverviewButton.Click += (_, _) => _contextController.OpenProjectOverviewFile();
        WorkbenchShell.ManagementPanels.RefreshCollaborationButton.Click += async (_, _) => await _contextController.LoadCollaborationAsync();
        WorkbenchShell.ManagementPanels.CreateCollaborationTaskButton.Click += async (_, _) => await _contextController.CreateCollaborationTaskAsync();
        WorkbenchShell.ManagementPanels.ClaimCollaborationFilesButton.Click += async (_, _) => await _contextController.ClaimCollaborationFilesAsync();
        WorkbenchShell.ManagementPanels.RecordCollaborationDecisionButton.Click += async (_, _) => await _contextController.RecordCollaborationDecisionAsync();
        WorkbenchShell.ManagementPanels.RecordCollaborationReviewButton.Click += async (_, _) => await _contextController.RecordCollaborationReviewAsync();
        WorkbenchShell.ManagementPanels.BuildCollaborationContextPackButton.Click += async (_, _) => await _contextController.BuildCollaborationContextPackAsync();
        WorkbenchShell.ManagementPanels.SendCollaborationMessageButton.Click += async (_, _) => await _contextController.SendCollaborationMessageAsync("post_message");
        WorkbenchShell.ManagementPanels.CreateCollaborationTaskInlineButton.Click += async (_, _) => await _contextController.CreateCollaborationTaskAsync();
        WorkbenchShell.ManagementPanels.ClaimCollaborationFilesInlineButton.Click += async (_, _) => await _contextController.ClaimCollaborationFilesAsync();
        WorkbenchShell.ManagementPanels.BuildCollaborationContextPackInlineButton.Click += async (_, _) => await _contextController.BuildCollaborationContextPackAsync();
        WorkbenchShell.ManagementPanels.RecordCollaborationDecisionInlineButton.Click += async (_, _) => await _contextController.RecordCollaborationDecisionAsync();
        WorkbenchShell.ManagementPanels.RecordCollaborationReviewInlineButton.Click += async (_, _) => await _contextController.RecordCollaborationReviewAsync();
        WorkbenchShell.ManagementPanels.SendCollaborationMessageInlineButton.Click += async (_, _) => await _contextController.SendCollaborationMessageAsync("post_message");
        WorkbenchShell.ManagementPanels.RequestCollaborationReviewMessageButton.Click += async (_, _) => await _contextController.SendCollaborationMessageAsync("request_model_review");
        WorkbenchShell.ManagementPanels.MarkCollaborationMessageReadButton.Click += async (_, _) => await _contextController.MarkSelectedCollaborationMessageReadAsync();
        WorkbenchShell.ManagementPanels.StartCollaborationWorkerButton.Click += async (_, _) => await _contextController.StartCollaborationWorkerAsync();
        WorkbenchShell.ManagementPanels.StopCollaborationWorkerButton.Click += (_, _) => _contextController.StopSelectedCollaborationWorker();
        WorkbenchShell.ManagementPanels.CollaborationWorkerAgentBox.SelectionChanged += (_, _) => _contextController.SyncCollaborationWorkerControls();
        ChatWorkspace.ChatDuplexToggle.Checked += async (_, _) => await _contextController.SetCollaborationAutoReplyAsync(true);
        ChatWorkspace.ChatDuplexToggle.Unchecked += async (_, _) => await _contextController.SetCollaborationAutoReplyAsync(false);
        WorkbenchShell.ManagementPanels.CollaborationTurnCapBox.LostFocus += async (_, _) => await _contextController.SaveCollaborationTurnCapFromPanelAsync();
        WorkbenchShell.ManagementPanels.CollaborationTurnCapBox.KeyDown += async (_, e) =>
        {
            if (e.Key == Key.Enter)
            {
                await _contextController.SaveCollaborationTurnCapFromPanelAsync();
                e.Handled = true;
            }
        };
        WorkbenchShell.ManagementPanels.PauseCollaborationTurnsButton.Click += async (_, _) => await _contextController.PauseCollaborationTurnsAsync();
        WorkbenchShell.ManagementPanels.RefreshAgentManagementButton.Click += async (_, _) => await _agentsController.LoadAgentManagementAsync();
        WorkbenchShell.ManagementPanels.SaveAgentManagementButton.Click += async (_, _) => await _agentsController.SaveAgentManagementAsync();
        WorkbenchShell.ManagementPanels.ExportRemoteModuleButton.Click += async (_, _) => await _agentsController.ExportRemoteModuleAsync();
        WorkbenchShell.ManagementPanels.PushRemoteModuleButton.Click += async (_, _) => await _agentsController.PushRemoteModuleAsync();
        WorkbenchShell.ManagementPanels.ExecuteRemoteModuleButton.Click += async (_, _) => await _agentsController.ExecuteRemoteModuleAsync();
        WorkbenchShell.ManagementPanels.OpenRemoteExportsButton.Click += (_, _) => _agentsController.OpenRemoteExportsFolder();
        WorkbenchShell.ManagementPanels.NewAgentButton.Click += (_, _) => _agentsController.NewAgent();
        WorkbenchShell.ManagementPanels.ApplyAgentButton.Click += (_, _) => _agentsController.ApplySelectedAgentFromEditor(showMessage: true);
        WorkbenchShell.ManagementPanels.AgentKnowledgeButton.Click += (_, _) => _agentsController.OpenSelectedAgentKnowledgeBase();
        WorkbenchShell.ManagementPanels.AgentChooseAssistantsButton.Click += (_, _) => _agentsController.OpenAgentAssistantMenu();
        WorkbenchShell.ManagementPanels.BrowseAgentKnowledgePathButton.Click += (_, _) => _agentsController.BrowseAgentKnowledgeBasePath();
        WorkbenchShell.ManagementPanels.DeleteAgentButton.Click += (_, _) => _agentsController.DeleteSelectedAgent();
        WorkbenchShell.ManagementPanels.NewAgentAdapterButton.Click += (_, _) => _agentsController.NewAgentAdapter();
        WorkbenchShell.ManagementPanels.ApplyAgentAdapterButton.Click += (_, _) => _agentsController.ApplySelectedAgentAdapterFromEditor(showMessage: true);
        WorkbenchShell.ManagementPanels.AgentAdapterUseForAgentButton.Click += (_, _) => _agentsController.UseSelectedAdapterForCurrentAgent();
        WorkbenchShell.ManagementPanels.DeleteAgentAdapterButton.Click += (_, _) => _agentsController.DeleteSelectedAgentAdapter();
        WorkbenchShell.ManagementPanels.NewExternalAssistantButton.Click += (_, _) => _agentsController.NewExternalAssistant();
        WorkbenchShell.ManagementPanels.ApplyExternalAssistantButton.Click += (_, _) => _agentsController.ApplySelectedExternalAssistantFromEditor(showMessage: true);
        WorkbenchShell.ManagementPanels.LaunchExternalAssistantButton.Click += (_, _) => _agentsController.LaunchSelectedExternalAssistant();
        WorkbenchShell.ManagementPanels.RunExternalAssistantPromptButton.Click += async (_, _) => await _agentsController.RunSelectedExternalAssistantPromptAsync();
        WorkbenchShell.ManagementPanels.StopExternalAssistantPromptButton.Click += (_, _) => _agentsController.StopExternalAssistantPrompt();
        WorkbenchShell.ManagementPanels.DeleteExternalAssistantButton.Click += (_, _) => _agentsController.DeleteSelectedExternalAssistant();
        WorkbenchShell.ManagementPanels.NewKnowledgeBaseButton.Click += async (_, _) => await _agentsController.NewKnowledgeBaseAsync();
        WorkbenchShell.ManagementPanels.ApplyKnowledgeBaseButton.Click += async (_, _) => await _agentsController.SaveSelectedKnowledgeBaseFromEditorAsync(showMessage: true);
        WorkbenchShell.ManagementPanels.OpenKnowledgeBaseFolderButton.Click += (_, _) => _agentsController.OpenSelectedKnowledgeBaseFolder();
        WorkbenchShell.ManagementPanels.BrowseKnowledgeBasePathButton.Click += (_, _) => _agentsController.BrowseKnowledgeBasePath();
        WorkbenchShell.ManagementPanels.ImportKnowledgeBaseFilesButton.Click += async (_, _) => await _agentsController.ImportKnowledgeBaseFilesAsync();
        WorkbenchShell.ManagementPanels.IndexKnowledgeBaseButton.Click += async (_, _) => await _agentsController.IndexSelectedKnowledgeBaseAsync();
        WorkbenchShell.ManagementPanels.RebuildAllKnowledgeIndexesButton.Click += async (_, _) => await _agentsController.RebuildAllKnowledgeIndexesAsync();
        WorkbenchShell.ManagementPanels.DeleteKnowledgeBaseButton.Click += async (_, _) => await _agentsController.DeleteSelectedKnowledgeBaseAsync();
        WorkbenchShell.ManagementPanels.NewKnowledgeSourceButton.Click += (_, _) => _agentsController.NewKnowledgeSource();
        WorkbenchShell.ManagementPanels.SaveKnowledgeSourceButton.Click += async (_, _) => await _agentsController.SaveKnowledgeSourceAsync();
        WorkbenchShell.ManagementPanels.SyncKnowledgeSourceButton.Click += async (_, _) => await _agentsController.SyncKnowledgeSourceAsync();
        WorkbenchShell.ManagementPanels.DeleteKnowledgeSourceButton.Click += async (_, _) => await _agentsController.DeleteKnowledgeSourceAsync();
        WorkbenchShell.ManagementPanels.BrowseKnowledgeSourcePathButton.Click += (_, _) => _agentsController.BrowseKnowledgeSourcePath();
        WorkbenchShell.ManagementPanels.NewRouteProfileButton.Click += (_, _) => _agentsController.NewRouteProfile();
        WorkbenchShell.ManagementPanels.ApplyRouteProfileButton.Click += (_, _) => _agentsController.ApplyRouteProfileOrShowError(showMessage: true);
        WorkbenchShell.ManagementPanels.DeleteRouteProfileButton.Click += (_, _) => _agentsController.DeleteSelectedRouteProfile();
        WorkbenchShell.ManagementPanels.NewRemoteTargetButton.Click += (_, _) => _agentsController.NewRemoteTarget();
        WorkbenchShell.ManagementPanels.ApplyRemoteTargetButton.Click += (_, _) => _agentsController.ApplySelectedRemoteTargetFromEditor(showMessage: true);
        WorkbenchShell.ManagementPanels.DeleteRemoteTargetButton.Click += (_, _) => _agentsController.DeleteSelectedRemoteTarget();
        WorkbenchShell.ToggleRightNavButton.Click += (_, _) => _workspaceController.ToggleRightNavigation();
        WorkspaceSidebar.WorkspaceNavList.SelectionChanged += _workspaceController.WorkspaceNavList_SelectionChanged;
        WorkspaceSidebar.SessionFilterBox.SelectionChanged += _workspaceController.SessionFilterBox_SelectionChanged;
        WorkbenchShell.RightNavList.SelectionChanged += _navigationController.RightNavList_SelectionChanged;
        WorkbenchShell.ManagementPanels.TaskSubNavList.SelectionChanged += _workspaceController.TaskSubNavList_SelectionChanged;
        WorkbenchShell.ManagementPanels.AgentSubNavList.SelectionChanged += _workspaceController.AgentSubNavList_SelectionChanged;
        WorkbenchShell.ManagementPanels.DiagnosticIssuesList.SelectionChanged += _navigationController.DiagnosticIssuesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.DailyItemsList.SelectionChanged += _navigationController.DailyItemsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.ContextSuggestionsList.SelectionChanged += _navigationController.ContextSuggestionsList_SelectionChanged;
        WorkbenchShell.ManagementPanels.AgentModelSelectBox.SelectionChanged += _agentsController.AgentModelSelectBox_SelectionChanged;
        WorkbenchShell.ManagementPanels.AgentAdaptersList.SelectionChanged += _agentsController.AgentAdaptersList_SelectionChanged;
        WorkbenchShell.ManagementPanels.KnowledgeBasesList.SelectionChanged += _agentsController.KnowledgeBasesList_SelectionChanged;
        WorkbenchShell.ManagementPanels.KnowledgeSourcesList.SelectionChanged += _agentsController.KnowledgeSourcesList_SelectionChanged;
        ChatWorkspace.QuickCommandBox.SelectionChanged += _workspaceController.QuickCommandBox_SelectionChanged;
        RegisterComposerWorkbenchHandlers();
        _workbenchController.RestoreWorkbenchPanelCollapsed();
        _workspaceController.ShowWorkspacePage("chat");
    }
}
