// <auto-generated>
// GENERATED FILE - do not edit by hand. Source: backend/app/realtime_contract.py; regenerate with scripts/generate_realtime_contract.py.
// </auto-generated>

namespace SpiritKinDesktop;

internal static class RealtimeContract
{
    public const string SchemaVersion = "spiritkin.realtime_contract.v1";

    internal static class Events
    {
        public const string AssistantMessage = "assistant.message";
        public const string AssistantDelta = "assistant.delta";
        public const string AssistantConfirmationRequested = "assistant.confirmation_requested";
        public const string AssistantExecutionUpdated = "assistant.execution_updated";
        public const string AssistantTaskUpdated = "assistant.task_updated";
        public const string AssistantProjectUpdated = "assistant.project_updated";
        public const string AssistantWorkUpdated = "assistant.work_updated";
        public const string RuntimeSnapshot = "runtime.snapshot";
        public const string RuntimeSubscribe = "runtime.subscribe";
        public const string RuntimeCapabilities = "runtime.capabilities";
        public const string RuntimeAggregatedState = "runtime.aggregated_state";
        public const string DesktopStateUpdated = "desktop.state_updated";
        public const string DesktopCollaborationUpdated = "desktop.collaboration_updated";
        public const string AvatarState = "avatar.state";
        public const string AvatarMotion = "avatar.motion";
        public const string AvatarAction = "avatar.action";
        public const string CollaborationMessage = "collaboration.message";
        public const string MemoryUpdated = "memory.updated";
        public const string ModelInteraction = "model.interaction";
        public const string PersonalityUpdated = "personality.updated";
        public const string PresenceUpdated = "presence.updated";
        public const string RelationshipUpdated = "relationship.updated";
        public const string ProactiveSuggested = "proactive.suggested";
        public const string ProactiveSuppressed = "proactive.suppressed";
        public const string ProactiveFeedback = "proactive.feedback";
        public const string OpeningBubblePresent = "opening_bubble.present";
        public const string SchedulerIntentDue = "scheduler.intent_due";
        public const string SchedulerIntentSuppressed = "scheduler.intent_suppressed";
        public const string VoiceCallState = "voice.call.state";
        public const string VoiceCallTranscript = "voice.call.transcript";
        public const string AsrSpeechStarted = "asr.speech_started";
        public const string AsrPartial = "asr.partial";
        public const string AsrFinal = "asr.final";
        public const string SpeechStarted = "speech.started";
        public const string SpeechEnded = "speech.ended";
        public const string SpeechInterrupted = "speech.interrupted";
        public const string SpeechPhoneme = "speech.phoneme";
        public const string SpeechViseme = "speech.viseme";
        public const string DeviceOpenclawStateUpdated = "device.openclaw_state_updated";
    }

    internal static class DefaultPorts
    {
        public const int Frontend = 8787;
        public const int EventBridge = 8765;
        public const int CommandGateway = 8788;
        public const int RemoteWorker = 8790;
        public const int AndroidEndpoint = 8791;
        public const int IosEndpoint = 8792;
    }

    internal static class PortEnvVars
    {
        public const string Frontend = "SPIRITKIN_FRONTEND_PORT";
        public const string EventBridge = "SPIRITKIN_EVENTS_PORT";
        public const string CommandGateway = "SPIRITKIN_COMMAND_PORT";
        public const string RemoteWorker = "SPIRITKIN_REMOTE_WORKER_PORT";
        public const string AndroidEndpoint = "SPIRITKIN_ANDROID_PORT";
        public const string IosEndpoint = "SPIRITKIN_IOS_PORT";
    }
}
