// GENERATED FILE - do not edit by hand. Source: backend/app/realtime_contract.py; regenerate with scripts/generate_realtime_contract.py.
(function (root) {
  "use strict";
  const contract = Object.freeze({
    schema: "spiritkin.realtime_contract.v1",
    events: Object.freeze({
      assistantMessage: "assistant.message",
      assistantDelta: "assistant.delta",
      assistantConfirmationRequested: "assistant.confirmation_requested",
      assistantExecutionUpdated: "assistant.execution_updated",
      assistantTaskUpdated: "assistant.task_updated",
      assistantProjectUpdated: "assistant.project_updated",
      assistantWorkUpdated: "assistant.work_updated",
      runtimeSnapshot: "runtime.snapshot",
      runtimeSubscribe: "runtime.subscribe",
      runtimeCapabilities: "runtime.capabilities",
      runtimeAggregatedState: "runtime.aggregated_state",
      desktopStateUpdated: "desktop.state_updated",
      desktopCollaborationUpdated: "desktop.collaboration_updated",
      avatarState: "avatar.state",
      avatarMotion: "avatar.motion",
      avatarAction: "avatar.action",
      collaborationMessage: "collaboration.message",
      memoryUpdated: "memory.updated",
      modelInteraction: "model.interaction",
      personalityUpdated: "personality.updated",
      presenceUpdated: "presence.updated",
      relationshipUpdated: "relationship.updated",
      proactiveSuggested: "proactive.suggested",
      proactiveSuppressed: "proactive.suppressed",
      proactiveFeedback: "proactive.feedback",
      openingBubblePresent: "opening_bubble.present",
      schedulerIntentDue: "scheduler.intent_due",
      schedulerIntentSuppressed: "scheduler.intent_suppressed",
      voiceCallState: "voice.call.state",
      voiceCallTranscript: "voice.call.transcript",
      asrSpeechStarted: "asr.speech_started",
      asrPartial: "asr.partial",
      asrFinal: "asr.final",
      speechStarted: "speech.started",
      speechEnded: "speech.ended",
      speechInterrupted: "speech.interrupted",
      speechPhoneme: "speech.phoneme",
      speechViseme: "speech.viseme",
      deviceOpenclawStateUpdated: "device.openclaw_state_updated",
    }),
    knownEventTypes: Object.freeze([
      "assistant.message",
      "assistant.delta",
      "assistant.confirmation_requested",
      "assistant.execution_updated",
      "assistant.task_updated",
      "assistant.project_updated",
      "assistant.work_updated",
      "runtime.snapshot",
      "runtime.subscribe",
      "runtime.capabilities",
      "runtime.aggregated_state",
      "desktop.state_updated",
      "desktop.collaboration_updated",
      "avatar.state",
      "avatar.motion",
      "avatar.action",
      "collaboration.message",
      "memory.updated",
      "model.interaction",
      "personality.updated",
      "presence.updated",
      "relationship.updated",
      "proactive.suggested",
      "proactive.suppressed",
      "proactive.feedback",
      "opening_bubble.present",
      "scheduler.intent_due",
      "scheduler.intent_suppressed",
      "voice.call.state",
      "voice.call.transcript",
      "asr.speech_started",
      "asr.partial",
      "asr.final",
      "speech.started",
      "speech.ended",
      "speech.interrupted",
      "speech.phoneme",
      "speech.viseme",
      "device.openclaw_state_updated",
    ]),
    defaultPorts: Object.freeze({
      frontend: 8787,
      event_bridge: 8765,
      command_gateway: 8788,
      remote_worker: 8790,
      android_endpoint: 8791,
      ios_endpoint: 8792,
    }),
    portEnvVars: Object.freeze({
      frontend: "SPIRITKIN_FRONTEND_PORT",
      event_bridge: "SPIRITKIN_EVENTS_PORT",
      command_gateway: "SPIRITKIN_COMMAND_PORT",
      remote_worker: "SPIRITKIN_REMOTE_WORKER_PORT",
      android_endpoint: "SPIRITKIN_ANDROID_PORT",
      ios_endpoint: "SPIRITKIN_IOS_PORT",
    }),
  });
  root.SPIRITKIN_CONTRACT = contract;
})(typeof window !== "undefined" ? window : globalThis);
